"use client";

import { defaultProps, insertOrUpdateBlock } from "@blocknote/core";
import { createReactBlockSpec } from "@blocknote/react";
import { editorSchema } from "./block-insertion";
import { AlertCircle } from "lucide-react";
import { ActionList as ActionListComponent } from "@/app/action-list";

export const ActionList = createReactBlockSpec(
  {
    type: "actionList",
    propSchema: {
      textAlignment: defaultProps.textAlignment,
      textColor: defaultProps.textColor,
    },
    content: "inline",
  },
  {
    render: (props) => {
      return (
        <div className="w-full">
          <ActionListComponent />
        </div>
      );
    },
  }
);

export const insertActionList = (
  editor: typeof editorSchema.BlockNoteEditor
) => ({
  title: "Action List",
  subtext: "With a list of actions generated by the AI and tuned for the user",
  onItemClick: () =>
    insertOrUpdateBlock(editor, {
      type: "actionList",
    }),
  aliases: [
    "actionlist",
    "action list",
    "action-list",
    "action",
    "list",
    "lists",
    "actions",
  ],
  group: "Action blocks",
  icon: <AlertCircle />,
});
